#What is the significance of the variables csv_file_location and report_file in the code snippet from the lab?
csv_file_location = "<csv-file-location>"
report_file = '<data-directory>' + '/updated_user_emails.csv'

#A. They store the username for accessing a remote server. - for accessing a remote server? I'm not sure about this...
#B. They define regular expressions for email domain validation. - email validation? I'm not sure about this either. I thought it was just regular emails...
#C. They store file paths for input and output csv files. - Well the file path above is just a path to the ending final result csv files...
#D. They contain the old and new domain names for email address replacement. - Do they really "contain" the data. Yes, one is the path to the old csv file of email addressed and the other is the new....

#My best guess is C...
